name: petzola
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adobe_xd: ^2.0.0+1
  nuts_activity_indicator: ^0.1.1
  delayed_display: ^2.0.0
  flutter_svg: ^0.21.0+1
  dependencies:
  pin_code_fields: ^7.3.0
  intl: ^0.17.0
  percent_indicator: "^2.1.7+2"
  flutter_custom_clippers: ^2.0.0
  image_picker: ^0.6.0+9
  dotted_border: ^2.0.0+1
  video_player: ^2.1.14
  flutter_rating_bar: ^4.0.0
  search_widget: ^1.0.2
  search_page: ^2.0.0+1
  google_maps_flutter: ^2.0.5
  location: ^4.1.1
  smooth_star_rating: 1.1.1
  geocoder: ^0.2.1
  geolocator: ^5.3.1
  custom_info_window: ^1.0.1
  clippy_flutter: ^1.1.1
  auto_localization: ^1.2.0
  shared_preferences: ^2.0.4
  translator: ^0.1.7
  path_provider: ^2.0.3
  flutter_slidable: ^0.6.0
  awesome_dialog: ^2.1.1
  fluttertoast: ^7.1.8
  file_picker: ^4.0.3
  mime: ^1.0.0
  flutter_launcher_icons: ^0.9.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/icons/splashlogo.png"
# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/
    - lib/lang/en.json
    - lib/lang/ar.json

  fonts:
    - family: sftsb
      fonts:
        - asset: fonts/SF-Pro-Text-Semibold.otf
    - family: sfdb
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.otf

    - family: sfdsb
      fonts:
        - asset: fonts/SF-Pro-Display-Semibold.otf
    - family: sftsb
      fonts:
        - asset: fonts/SF-Pro-Text-Semibold.otf
    - family: sfdm
      fonts :
        - asset: fonts/SF-Pro-Display-Medium.otf

    - family: sftr
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
    - family: sfdr
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
